kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
- name: docker
  image: plugins/docker
  settings:
    username: wanglei4966
    password: dajiaDAJIA1
    repo: wanglei4966/repository
    tags: latest
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 46.137.226.188
    username: ubuntu
    password: ubuntu
    port: 22
    script:
      - sudo docker pull wanglei4966/repository:latest
      - sudo docker run -p 8081:8081 --restart=always --name=test wanglei4966/repository:latest

  