kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - echo hello
  - echo world
- name: docker
  image: plugins/docker
  settings:
    username: wanglei4966
    password: dajiaDAJIA1
    repo: wanglei4966/repository
    tags: latest
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host: foo.com
      username: root
      port: 22
      key:
        from_secret: ssh_key
      script:
        - echo hello
        - echo world

  