kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - echo hello
  - echo world
- name: docker
  image: plugins/docker
  settings:
    username: wanglei4966
    password: dajiaDAJIA1
    repo: wanglei4966/repository
    tags: latest
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 46.137.226.188
    username: ubuntu
    port: 22
    key:
      from_secret: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA7wxR6BBRgjVicG6Ghc3b3aqpBsw72beKtHYGsMVkEk28AI4MXwqV
GnBnNe8blbW+T+Bn6V1FOTEF3o+JklPViIVQ0dFua749DiEQUjr968DWzk1kz2GvYfsoRX
RFwGhk6gNdlB1uAGHMaZ2x0rO+ExYeEjPow618itl4Z8Tvb6qztwvkMKbuhzg7UlEHrvZu
HLKpdhX6bdGtb6aQb1r+hMuvVjfxyMN7JqrV9hR5iueg3BXdN0GRfO41RIaRovFakz+7Qx
/5aZUGFhFZR7NllSaKPWwfboYFn4GJd8JElOH7miLhc3jGcrxUV46j3M63eolZjvjlA5PY
7irMRJzMoWVztVpBAsfkQysuElvvrsGX+50lWJakKow5fy0CCu744SeFak1SKVWiOgPFX2
3wCoiNhkUcw12+84r3c9Rp6nzKc+1FdIfyno81u0k1WLqlVqhicpfw9jF1jsEIOG8j09Bp
hckcyzm8zV/AIrwzzMaEJnq8TMti0k9h81x984BBAAAFmEk+b69JPm+vAAAAB3NzaC1yc2
EAAAGBAO8MUegQUYI1YnBuhoXN292qqQbMO9m3irR2BrDFZBJNvACODF8KlRpwZzXvG5W1
vk/gZ+ldRTkxBd6PiZJT1YiFUNHRbmu+PQ4hEFI6/evA1s5NZM9hr2H7KEV0RcBoZOoDXZ
QdbgBhzGmdsdKzvhMWHhIz6MOtfIrZeGfE72+qs7cL5DCm7oc4O1JRB672bhyyqXYV+m3R
rW+mkG9a/oTLr1Y38cjDeyaq1fYUeYrnoNwV3TdBkXzuNUSGkaLxWpM/u0Mf+WmVBhYRWU
ezZZUmij1sH26GBZ+BiXfCRJTh+5oi4XN4xnK8VFeOo9zOt3qJWY745QOT2O4qzESczKFl
c7VaQQLH5EMrLhJb767Bl/udJViWpCqMOX8tAgru+OEnhWpNUilVojoDxV9t8AqIjYZFHM
NdvvOK93PUaep8ynPtRXSH8p6PNbtJNVi6pVaoYnKX8PYxdY7BCDhvI9PQaYXJHMs5vM1f
wCK8M8zGhCZ6vEzLYtJPYfNcffOAQQAAAAMBAAEAAAGABAuMU0X7ax2mJcrpAdii8NRTee
b42E1Pzo/0uwcME3c3SDcfJHiUX1cpl/MM33Ks3sMoXv2SD06yD7sUE+LRSTcgT/ygRrh4
ZgXPNeUDqPqhZ+pNW2kGw7yxSMOX7pKVqpQWAEyjMOR2xg7CFJOwEricF6jDNpR3+A2ICR
F/D7+uvNk5qk0Y2jbsYg829xH6eQfY8EOc8kDLE4mZBhlfFzYvKGFX+RK9wcDAUCK2j9At
m6vPC4FTie6p/hfc3QoCev3urGVUMqbHynCKF55PakwHpiKCxv37/yA/ZudV5S4a7alv4s
RGxEUtkktmklq5ov5q2+m8EyF9nOMnWqsjll4CWUQQw5LYBgwqVGkJft6fQR6cMtjq7smk
e434dMTzM0P3KY3IWiz1ntnjAeQpXpqGiurdOp1X+XWXHfZtjGZFG4cJJwNdacqLnDlpzA
IqwUc2hkgdmtw0lsq6KxrtulOEOYsLePe7GwvzjAKTTlegqXv7Kme0E753mKXpF6rBAAAA
wQC26SpCN4mWClOgh1qMaTzLTU2mEbog9Jas0Ar0ybZLSAQ0+RMC94GTN3bOMBLTDdn6DN
axauUJFQKcVpjFDT5RBmwVLHk6gMLevWwFTrWBgRqCsQBmknmHlhTrQgjYY0H7Per8hcNQ
9R8Q8sn8MVtbH2Y+EiY4v76Pwj7wNUs/jxJHhYTHlJpT7YGHbqtfk/hE4ZeWVUXERNJ76c
7iHBEvSit9HP+2v6AD7ygARBVt4NM/cyPbPvQVxPX2Id8IU84AAADBAPp/CD6iIeuKpzo1
3jDyYHryr3FjrXhSfLAIBYb1Q9eeggZB2y1ls/K2F7qhZzN5J5y4YU9CYrwm1fsN3+Nglq
UZcBmsKSVSf0Gch3VVZkJHwIo03gy4uRzcrAhTuPna90Px7D8j7SRZHCyI4IUAroPZ0P7b
AQLpjeno4jY8/RjOCbUCKM0lwebT1z/58L3KvlnVbrdVv2glxLjPDkLIe5nAkQi1Vl6Z5P
uilKacnV155G8P14K2u2QqhKG2V7alSQAAAMEA9EzlQ72lor+1JEOydCaUxk4uyMOs8LdY
qiqtdOasIiPTMmF5pV+WaeBqcNfMwuOHnwQE3mSQZCZvIC4uNblELkBOkTJbWm7LD9NaiN
ufX/vGa6rq2vW+zOsL6xY5bgMpf9rHrZkkZPF9jiu/vU1XDFzBRjleH21cexNKquIZS5t5
7NJ8cMlG15jhprOtihgfcLZfplXXTXRjRkplkaztpn/n8OVfd6hd/OSBmLgZVtiC1fh6g7
SDjAcB/uROChs5AAAAG3dhbmcubGVpQENMU0dMUDE5MDAyMi5sb2NhbAECAwQFBgc=
    script:
      - echo hello
      - echo world

  