kind: pipeline
type: docker
name: default

steps:
- name: build
  image: aipline
  commands:
  - echo hello
  - echo world
- name: docker
  image : plugins/docker
  settings:
    username: wanglei4966
    password: dajiaDAJIA1
    repo: wanglei4966/repository
    tags: latest