kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - echo hello
  - echo world
- name: docker
  image: plugins/docker
  settings:
    username: wanglei4966
    password: dajiaDAJIA1
    repo: wanglei4966/repository
    tags: latest
- name: deploy
    image: appleboy/drone-ssh
    settings:
      host: localhost
      username: wang.lei
      key:
        from_secret: ssh_key
      port: 22
      script:
        - echo "hello"
        - echo "world"