kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
- name: push
  image: plugins/docker
  settings:
    username: wanglei4966
    password: dajiaDAJIA1
    repo: wanglei4966/repository
    tags: latest
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: http://ec2-46-137-226-188.ap-southeast-1.compute.amazonaws.com
    username: ubuntu
    password: ubuntu
    port: 22
    script:
      - sudo docker pull wanglei4966/repository:latest
      - sudo docker stop test || true && sudo docker rm test || true
      - sudo docker run -d -p 8081:8081 --restart=always --name=test wanglei4966/repository:latest
      - exit 0
  